version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: odoo
    container_name: odoo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - odoo

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - odoo
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - odoo
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_DATABASE}
      - PMA_PASSWORD=${DB_PASSWORD}
      
  nginx:
    image: nginx:alpine
    container_name: odoo-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - odoo

networks:
  odoo:
    driver: bridge