version: "3.7"
services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: bitnami/mysql:5.7
    restart: always
    container_name: bitnami-mysql
    environment:
      - MYSQL_DATABASE=acts
      - MYSQL_USER=suttipong
      - MYSQL_PASSWORD=gYRdC0qxua6t01hJFZ8Ok983s
      - MYSQL_ROOT_PASSWORD=gYRdC0qxua6t01hJFZ8Ok983s
    networks:
      - travellist
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - travellist
    environment:
      - PMA_HOST=db
      - PMA_USER=suttipong
      - PMA_PASSWORD=gYRdC0qxua6t01hJFZ8Ok983s
      
  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - travellist

networks:
  travellist:
    driver: bridge