<?php

function DateThai($strDate){

$strYear = date("Y",strtotime($strDate))+543;

$strMonth= date("n",strtotime($strDate));

$strDay= date("j",strtotime($strDate));

$strHour= date("H",strtotime($strDate));

$strMinute= date("i",strtotime($strDate));

$strSeconds= date("s",strtotime($strDate));

$strMonthCut = Array("","ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค.");

$strMonthThai=$strMonthCut[$strMonth];

return "$strDay $strMonthThai $strYear";
}

?>
<html>
<head>
	<title>พิมพ์บาร์โค๊ด</title>
	<meta charset="utf-8">
	<link href="/assets/fonts/fontlabel.css" rel="stylesheet">
	<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<style>
	<style>
		/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on March 16, 2021 */

@font-face {
    font-family: 'db_heaventroundedbold_cond_it';
    src: url('/prnotiasset/db_heaventrounded_bd_cond_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_bd_cond_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedbold_cond';
    src: url('/prnotiasset/db_heaventrounded_bd_cond_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_bd_cond_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedbold_it';
    src: url('/prnotiasset/db_heaventrounded_bd_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_bd_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedbold';
    src: url('/prnotiasset/db_heaventrounded_bd_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_bd_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedblack_it';
    src: url('/prnotiasset//prnotiasset/db_heaventrounded_blk_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_blk_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedblack';
    src: url('/prnotiasset/db_heaventrounded_blk_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_blk_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}


@font-face {
    font-family: 'db_heaventroundedcond_it';
    src: url('/prnotiasset/db_heaventrounded_cond_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_cond_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedcond';
    src: url('/prnotiasset/db_heaventrounded_cond_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_cond_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundeditalic';
    src: url('/prnotiasset/db_heaventrounded_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedmed_cond_it';
    src: url('/prnotiasset/db_heaventrounded_med_cond_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_med_cond_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'db_heaventroundedmed_cond';
    src: url('/prnotiasset/db_heaventrounded_med_cond_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_med_cond_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}

@font-face {
    font-family: 'db_heaventroundedmed_it';
    src: url('/prnotiasset/db_heaventrounded_med_it_v3.2-webfont.woff2') format('woff2'),
         url('/prnotiasset/db_heaventrounded_med_it_v3.2-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;

}
*,html,body,h1,p{
	font-family: 'db_heaventroundedbold';
}
		.boxbarcode{
			width: 8cm !important;
			height: 3.8cm !important;
			border: 1px solid #EEE;
			margin-bottom: 3mm;
			background-image: url('/template-barcode.png');
			background-size: contain;
			-webkit-print-color-adjust: exact;
		}
		.boxbarcode-brand{
			font-family: 'db_heaventroundedbold' !important;
			color: rgb(41,62,128);
			position: relative;
			left: 0.5cm;
			top:-0.5cm;
			z-index: 999;
		}
		.boxbarcode-productname{
			font-family: 'db_heaventroundedregular' !important;
			color: rgb(41,62,128);
			font-size: 1.3em;
		}
		.boxbarcode-price{
			font-family: 'db_heaventroundedbold' !important;
			font-size: 3em;
			color: rgb(224,104,136);
			
		}
		.boxprice{
text-align: center;
    left: 2cm;
    top: -1.55cm;
    z-index: 999;
    position: relative;
		}
		.boxproductname{
			    position: relative;
    left: 0.5cm;
    top: -3.9cm;
    width: 3.5cm;
    word-break: break-word;
    z-index: 999;

		}

		page[size="barcode-page"] {
			background: white;
			width: 21cm;
			height: 29.7cm;
			display: block;
			margin: 0 auto;
		}
		@media print {
			body, page[size="barcode-page"] {
				margin: 0;
				box-shadow: 0;
			}
			* {
				-webkit-transition: none !important;
				transition: none !important;
			}
			@page {size: landscape}
		}
		.box-item{
			width: 9.5cm;
			background-image: url('/printpronotification.jpg');
			background-size: cover;
			height: 9.5cm;
			text-align: center;
		}
	</style>
</head>
<body>
@if($type=="single")	
<div class="box-item">
<div class="top"  style="width: 9cm;position: relative;padding: 1cm;left: 0.2cm;top: 0.7cm;text-align: center;text-overflow: ellipsis;height: 7.5cm;">
	<span  style="color:rgb(237,32,36);">{{$promotion->description}}</span>
		
</div>
<div class="bottom" style="width: 7cm; height: 1cm; position: relative; left: 1.2cm; top: 0.2cm; text-align: center; ">
	<?php
		$product = $promotion->getProduct;
		$product = \App\Http\Controllers\BrandController::getProductData($product[0]->product_id);
		$product = $product->getProduct;

	?>
	<span  style="color:rgb(246,200,32);  margin-bottom: 0; text-shadow: rgb(222 118 52) 3px 1px 0px;">{{$product->name}}</span>
	<p id="fit2" style="margin-top: 0; color: rgb(233,158,197); font-size: 1.5em;">{{DateThai($promotion->startdate)}} - {{DateThai($promotion->enddate)}}</p>
</div>
</div>
@else
<?php
	$count = 0;
?>
<table>
@foreach($promotions as $promotion)
<?php
if($count%3==0){
	echo "<tr>";
}
$count++;
?>

<td>
<div class="box-item">
<div class="top"  style="width: 9cm;position: relative;padding: 1cm;left: 0.2cm;top: 0.7cm;text-align: center;text-overflow: ellipsis;height: 7.5cm;">
	<span  style="color:rgb(237,32,36);">{{$promotion->description}}</span>
		
</div>
<div class="bottom" style="width: 7cm; height: 1cm; position: relative; left: 1.2cm; top: 0.2cm; text-align: center; ">
	<?php
		$product = $promotion->getProduct;
		if(isset($product[0])){
			$product = \App\Http\Controllers\BrandController::getProductData($product[0]->product_id);
			$product = $product->getProduct;
		}else{
			continue;
		}
		
	?>
	<span  style="color:rgb(246,200,32);  margin-bottom: 0; text-shadow: rgb(222 118 52) 3px 1px 0px;">{{$product->name}}</span>
	<p id="fit2" style="margin-top: 0; color: rgb(233,158,197); font-size: 1.5em;">{{DateThai($promotion->startdate)}} - {{DateThai($promotion->enddate)}}</p>
</div>
</div>
</td>
<?php
if($count%3==0){
	echo "</tr>";
}
?>
@endforeach
@endif
</table>

</body>
<script type="text/javascript">
	//window.print();
</script>
</script>
<script
src="//code.jquery.com/jquery-2.2.4.js"
integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
crossorigin="anonymous"></script>
<script src="/js/jquery.textfill.js"></script>
<script>
	$('.top').textfill({
		maxFontPixels: 0
	});
	$('.bottom').textfill({
		maxFontPixels: 0
	});
</script>

</html>



