<?php

function DateThai($strDate){

	$strYear = date("Y",strtotime($strDate))+543;

	$strMonth= date("n",strtotime($strDate));

	$strDay= date("j",strtotime($strDate));

	$strHour= date("H",strtotime($strDate));

	$strMinute= date("i",strtotime($strDate));

	$strSeconds= date("s",strtotime($strDate));

	$strMonthCut = Array("","ม.ค.","ก.พ.","มี.ค.","เม.ย.","พ.ค.","มิ.ย.","ก.ค.","ส.ค.","ก.ย.","ต.ค.","พ.ย.","ธ.ค.");

	$strMonthThai=$strMonthCut[$strMonth];

	return "$strDay $strMonthThai $strYear";
}
?>
<html>
<head>
	<title>พิมพ์บาร์โค๊ด</title>
	<meta charset="utf-8">
	<link href="//fonts.googleapis.com/css?family=Kanit&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<style>
		/*! Generated by Font Squirrel (https://www.fontsquirrel.com) on March 16, 2021 */

		@font-face {
			font-family: 'db_heaventroundedbold_cond_it';
			src: url('/prnotiasset/db_heaventrounded_bd_cond_it_v3.2-webfont.woff2') format('woff2'),
			url('/prnotiasset/db_heaventrounded_bd_cond_it_v3.2-webfont.woff') format('woff');
			font-weight: normal;
			font-style: normal;

		}

		@font-face {
			font-family: 'db_heaventroundedbold_cond';
			src: url('/prnotiasset/db_heaventrounded_bd_cond_v3.2-webfont.woff2') format('woff2'),
			url('/prnotiasset/db_heaventrounded_bd_cond_v3.2-webfont.woff') format('woff');
			font-weight: normal;
			font-style: normal;

		}

		@font-face {
			font-family: 'db_heaventroundedbold_it';
			src: url('/prnotiasset/db_heaventrounded_bd_it_v3.2-webfont.woff2') format('woff2'),
			url('/prnotiasset/db_heaventrounded_bd_it_v3.2-webfont.woff') format('woff');
			font-weight: normal;
			font-style: normal;

		}

		@font-face {
			font-family: 'db_heaventroundedbold';
			src: url('/prnotiasset/db_heaventrounded_bd_v3.2-webfont.woff2') format('woff2'),
			url('/prnotiasset/db_heaventrounded_bd_v3.2-webfont.woff') format('woff');
			font-weight: normal;
			font-style: normal;

		}

		@font-face {
			font-family: 'db_heaventroundedblack_it';
			src: url('/prnotiasset//prnotiasset/db_heaventrounded_blk_it_v3.2-webfont.woff2') format('woff2'),
			url('/prnotiasset/db_heaventrounded_blk_it_v3.2-webfont.woff') format('woff');
			font-weight: normal;
			font-style: normal;

		}

		*,h1,h2,h3,h4,p{
			font-family: 'db_heaventroundedbold';
		}
		.boxbarcode{
			width: :48.5mm !important;
			height: 25.4mm !important;
			text-align: center;
			line-height: 2.85px;
			padding-bottom: 16px;
		}
		.boxbarcode img{
			margin-bottom: -5px;
			height: 12mm;
		}
		p{
			font-size: 11px;
		}
		page[size="barcode-page"] {
			background: white;
			width: 21cm;
			height: 29.7cm;
			display: block;
			margin: 0 auto;
		}
		table{
			margin-top: 2mm;
			width: 100%;
		}
		.pricefix{
			margin-bottom: 1px;
		}

		@media print {
			body, page[size="barcode-page"] {
				margin: 0;
				box-shadow: 0;
			}
			* {
				-webkit-transition: none !important;
				transition: none !important;
			}
		}

	</style>
</head>
<body>

	@if($type=="single")
	<div style="background-image: url('/printpromotion.jpg'); background-size: cover; width: 8cm; height:3.98cm; text-align: center; border:1px solid black;">
		<div  style="margin-top:0cm; margin-left:1.25cm; width: 80%; padding: 0.2cm;">
			<div class="top" style="position:relative; width:80%; text-align: center; margin:0 auto; min-height:3cm;">
				<span style="margin: 0; text-align: center;">{{$productdata->getUser->brand_name}} {{$productdata->name}}</span>
			</div>
			<div class="bottom" style="position:relative; width:100%;">
				<span style="margin: 0;">ลดเหลือ <font style="background:black; color: #FFF;"> {{$product->price}}.-</font> จากปกติ {{$productdata->price}}.-</span>
			</div>
		</div>

	</div>
	@else
	<div class="row">
		<?php
			$count = 0;
		?>
		@foreach($products as $product)
		<?php
			if($count%30==0&&$count!=0){
				echo "<div class='col-12' style='padding:15px;'></div>";
			}
			$productdata = $product->getProductVariant;
			if(isset($productdata)){
				$productdata = $productdata->getProduct;
				$count++;
			}
		?>
			@if(isset($productdata))
				<div class="col-4">
					<div style="background-image: url('/printpromotion.jpg'); background-size: cover; width: 8cm; height:3.98cm; text-align: center; border:1px solid black;">
						<div  style="margin-top:0cm; margin-left:1.25cm; width: 80%; padding: 0.2cm;">
							<div class="top" style="position:relative; width:80%; text-align: center; margin:0 auto; min-height:3cm;">
								<span style="margin: 0; text-align: center;">{{$productdata->getUser->brand_name}} {{$productdata->name}}</span>
							</div>
							<div class="bottom" style="position:relative; width:100%; margin-top:-5px;">
								<span style="margin: 0;">ลดเหลือ <font style="background:black; color: #FFF;"> {{$product->price}}.-</font> จากปกติ {{$productdata->price}}.-</span>
							</div>
						</div>

					</div>
				</div>
			@endif
		@endforeach
	</div>


	@endif

</body>
<script type="text/javascript">
	//window.print();
</script>
<script
src="//code.jquery.com/jquery-2.2.4.js"
integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
crossorigin="anonymous"></script>
<script src="/js/jquery.textfill.js"></script>
<script>
	$('.top').textfill({
		maxFontPixels: 0
	});
	$('.bottom').textfill({
		maxFontPixels: 0
	});
</script>

</html>



